warning about logrotation of wtmp file

diff --git a/session-packages b/session-packages
--- a/session-packages
+++ b/session-packages
@@ -23,6 +23,10 @@ declare -a pkgs_to_remove
 
 function fetchCurrSessionPkgs {
     curr_session_start_time=$(getCurrSessionTimestamp "$1")
+    if [ "$current_session_start_time" = "" ]; then
+	echo "Couldn't get past reboots timestamp. Perhaps /var/log/wtmp was logrotated?" >&2
+	exit 1
+    fi
     curr_session_pkgs=($(getPkgsSince $curr_session_start_time))
 }
 
